export const courseTypes = ["gn", "org"];
export const courseStatuses = ["draft", "published"];

export const courseSearchableFields = [
  "title",
  "description",
  "tags",
  "creator.externalId",
  "categories",
  "levels",
  "languages",
];

export const courseFilterableFields = [
  "searchTerm",
  "tags",
  "creator.externalId",
  "categories",
  "levels",
  "languages",
  "ratings",
];

export const languages = [
  "🇦🇫 Pashto",
  "🇦🇱 Albanian",
  "🇩🇿 Arabic",
  "🇦🇷 Spanish",
  "🇦🇺 English",
  "🇦🇹 German",
  "🇧🇩 Bangla",
  "🇧🇷 Portuguese",
  "🇨🇦 English",
  "🇨🇳 Chinese",
  "🇨🇴 Spanish",
  "🇨🇿 Czech",
  "🇩🇪 German",
  "🇪🇬 Arabic",
  "🇪🇸 Spanish",
  "🇫🇷 French",
  "🇬🇧 English",
  "🇬🇷 Greek",
  "🇮🇳 Hindi",
  "🇮🇩 Indonesian",
  "🇮🇹 Italian",
  "🇯🇵 Japanese",
  "🇰🇷 Korean",
  "🇲🇾 Malay",
  "🇲🇽 Spanish",
  "🇳🇬 Hausa",
  "🇳🇴 Norwegian",
  "🇵🇰 Urdu",
  "🇵🇭 Filipino",
  "🇷🇺 Russian",
  "🇸🇦 Arabic",
  "🇸🇬 Chinese",
  "🇿🇦 Zulu",
  "🇹🇭 Thai",
  "🇹🇷 Turkish",
  "🇺🇦 Ukrainian",
  "🇺🇸 English",
  "🇻🇳 Vietnamese",
  "🇿🇲 Bemba",
  "🇿🇼 Shona",
];

export const courseLevels = ["🌱 Beginner", "🚧 Intermediate", "🚀 Advance"];

export const courseCategories = [
  "🌐 Web Development",
  "📱 Mobile App Development",
  "📊 Data Science",
  "🤖 Machine Learning",
  "🧠 Artificial Intelligence",
  "🎮 Game Development",
  "🎨 Graphic Design",
  "💼 Digital Marketing",
  "📸 Photography",
  "🎵 Music Production",
  "🗣️ Language Learning",
  "🚀 Personal Development",
  "💼 Business",
  "📈 Finance and Accounting",
  "💻 IT and Software",
  "💪 Health and Fitness",
  "🌴 Lifestyle",
  "📚 Academic",
  "🔧 Engineering",
  "🖊️ Writing",
  "🍳 Cooking",
  "👶 Parenting",
  "🥋 Self Defense",
  "🧘 Yoga",
  "💃 Dance",
  "🎨 Drawing and Painting",
  "🌿 Gardening",
  "🔨 DIY and Crafts",
  "💄 Fashion and Beauty",
  "🐾 Pet Care",
  "✈️ Travel",
  "📸 Photography",
  "🎬 Video Editing",
  "🗣️ Presentation Skills",
  "🎙️ Public Speaking",
  "⏰ Time Management",
  "👨‍💼 Leadership",
  "🤝 Negotiation",
  "💰 Sales",
  "🔍 SEO (Search Engine Optimization)",
  "📱 Social Media Marketing",
  "🔗 Blockchain",
  "🔐 Cybersecurity",
  "☁️ Cloud Computing",
  "🌐 Networking",
  "🎮 Game Design",
  "🎨 UI/UX Design",
  "🎥 3D and Animation",
  "🕶️ AR/VR (Augmented Reality/Virtual Reality)",
  "🤖 Robotics",
  "💰 Personal Finance",
  "💹 Investing",
  "💱 Cryptocurrency",
  "📈 Data Analysis",
  "📊 Business Analytics",
  "📊 Excel",
  "🐍 Python Programming",
  "☕ Java Programming",
  "🔍 C++ Programming",
  "💎 Ruby Programming",
  "📱 Swift Programming",
  "⚛️ React.js",
  "🅰️ Angular",
  "🚀 Vue.js",
  "🟢 Node.js",
  "🎸 Guitar",
  "🎹 Piano",
  "🎤 Singing",
  "✍️ Drawing and Sketching",
  "🎨 Watercolor Painting",
  "🎨 Acrylic Painting",
  "🏢 Interior Design",
  "🍳 Cooking and Baking Techniques",
  "🌱 Vegan and Vegetarian Cooking",
  "💪 Fitness Training",
  "🧘 Meditation",
  "🧠 Mindfulness",
  "🔥 Stress Management",
  "👪 Parenting Tips and Techniques",
  "👦 Child Psychology",
  "🚑 First Aid",
  "🗣️ Foreign Language Teaching",
  "📚 English Language Teaching (ESL)",
  "🎨 Web Design",
  "🗃️ Database Design",
  "📱 Mobile App Design",
  "🚀 Virtual Reality Design",
  "📊 Digital Marketing Analytics",
  "💰 Social Media Advertising",
  "📧 Email Marketing",
  "📝 Content Marketing",
  "👩‍🏫 Influencer Marketing",
  "🛍️ E-commerce",
  "⛓️ Supply Chain Management",
  "🤖 AI for Business",
  "🚀 Quantum Computing",
  "🌐 Internet of Things (IoT)",
  "🛡️ Ethical Hacking",
  "🔑 Penetration Testing",
  "💻 Front-End Web Development",
  "💾 Back-End Web Development",
  "🔧 Full-Stack Web Development",
  "🧪 Software Testing",
  "🎮 Video Game Programming",
  "🎨 Game Art",
  "👾 Character Design",
  "📱 App Development for iOS and Android",
  "🤖 Arduino Programming",
  "🥧 Raspberry Pi",
  "🛡️ Cybersecurity Fundamentals",
  "📊 Data Visualization",
  "📈 Statistical Analysis",
  "🔗 Blockchain Development",
  "💹 Cryptocurrency Trading",
  "💱 Forex Trading",
  "📉 Options Trading",
];
