import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // offset navbar height
  return (
    <section className="bg-slate-100 text-gray-950 dark:bg-gray-950 dark:text-slate-100 py-2 max-h-full h-screen">
      {children}
    </section>
  );
}
